[build]
  command = "npm install" # Ensure dependencies are installed
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'unsafe-hashes' 
        'sha256-tVMTDnS1ErEZ3zq1Wwn6OUqmnt3hTks4FUmFSYhoOlU=' 
        'sha256-yei5Fza+Eyx4G0smvN0xBqEesIKumz6RSyGsU3FJowI=' 
        'sha256-KOQQ/uRMMco8bVeGYGNAQAKyC7h9NJgSRtmL7EapEKg=' 
        'sha256-e357n1PxCJ8d03/QCSKaHFmHF1JADyvSHdSfshxM494=' 
        'sha256-5DA+a07wxWmEka9IdoWjSPVHb17Cp5284/lJzfbl8KA=' 
        'sha256-/5Guo2nzv5n/w6ukZpOBZOtTJBJPSkJ6mhHpnBgm3Ls=' 
        https://js.stripe.com https://*.stripe.com https://m.stripe.network;
      style-src 'self' 'unsafe-inline' 'unsafe-hashes' 
        'sha256-GsQC5AaXpdCaKTyWbxBzn7nitfp0Otwn7I/zu0rUKOs=' 
        https://js.stripe.com https://*.stripe.com https://m.stripe.network;
      connect-src 'self' https://*.stripe.com https://m.stripe.network wss://*.stripe.com;
      img-src 'self' data: https://*.stripe.com https://m.stripe.network;
      font-src 'self' https://js.stripe.com https://*.stripe.com https://m.stripe.network;
      frame-src https://checkout.stripe.com https://*.stripe.com https://m.stripe.network;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[functions]
  node_bundler = "esbuild" # Optimize function bundling